---
title: "'Using DiffCorr package to analyze and visualize differential correlation in biological networks' support page"
output:
  html_document:
    toc: true
    theme: united
---

# Preface

This is a support page about **"Using DiffCorr package to analyze and visualize differential correlation in biological networks"** - Book chapter in "Challenges of Computational Network Analysis with R". Editors: Matthias Dehmer, Yongtang Shi, and Frank Emmert-Streib. WILEY. 

[linkto publisher web page](http://as.wiley.com/WileyCDA/WileyTitle/productCd-3527339582.html)  
[linkto Amazon]()

> The R package DiffCorr affords users a simple and effective framework to detect differential correlations between 2 conditions in omics data. 
> The approach is useful for the first step towards inferring causal relationships and detecting biomarker candidates.

We have used many R (and Bioconductor) packages in the book chapter, and those packages are updating day by day.

Here we keep you informed on those updates and additional instructions upsupported in the book chapter.

We will revise this page continually. If you have a question about this book and support page, feel free to contact kozo.nishida@gmail.com or twitter [\@kozo2](https://twitter.com/kozo2).

# Important announcement

- Jun 16, 2015 **ath1121501.db** package in section **3.5** does not work on version **3.1.2**. This bug is fixed in version **3.1.4**. For more detail, please see https://support.bioconductor.org/p/68997/ .

# R code files

You can [download the R scripts](https://github.com/afukushima/afukushima.github.io/tree/master/diffcorrbook) used in this book chapter.

# Updates

- Sep 3, 2015 added publisher information.
- July 28, 2015 published this support page.

# Related software updates

- Jun 27, 2015 **ath1121501.db** 3.1.4 released.


# Integrating R and Cytoscape

By adding cyREST app (http://apps.cytoscape.org/apps/cyrest), you can programmatically controll Cytoscape with R. You can reproduce the book chapter Figure 4.B and Figure 7.B with just running the R script in (https://github.com/afukushima) without controlling Cytoscape GUI manually.
